/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Academia_do_Programador;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.text.MaskFormatter;

/**
 * @author JX
 */
public class Janela extends javax.swing.JFrame {

    ArrayList<Equipamentos> equipamentos = new ArrayList();
    ArrayList<Chamados> chamados = new ArrayList();

    public Janela() {
        initComponents();
        try {
            MaskFormatter maskData = new MaskFormatter("##/##/####");
            MaskFormatter maskData2 = new MaskFormatter("##/##/####");
            maskData.install(tf_data_fabr);
            maskData2.install(tf_data_ab);
            
            Date data;                                                              //////EXCLUIR
            SimpleDateFormat f = new SimpleDateFormat("dd/MM/yyyy");
            data = f.parse("27/04/2010");

            Equipamentos equipa = new Equipamentos("1", 1, 1, data, "sexo");
            equipamentos.add(equipa);

        } catch (ParseException ex) {
            System.out.println("bo nas mask");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        Abas = new javax.swing.JTabbedPane();
        panel_equipamentos = new javax.swing.JPanel();
        tf_nome = new javax.swing.JTextField();
        tf_preco = new javax.swing.JTextField();
        tf_nr_serie = new javax.swing.JTextField();
        tf_fabricante = new javax.swing.JTextField();
        tf_data_fabr = new javax.swing.JFormattedTextField();
        bt_inserire = new javax.swing.JButton();
        bt_editare = new javax.swing.JButton();
        bt_removere = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        table_chamados1 = new javax.swing.JTable();
        panel_chamados = new javax.swing.JPanel();
        bt_removerc = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        tf_chamado = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        tf_desc = new javax.swing.JTextField();
        tf_data_ab = new javax.swing.JFormattedTextField();
        bt_inserirc = new javax.swing.JButton();
        bt_editarc = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        table_chamados = new javax.swing.JTable();
        cb_equip = new javax.swing.JComboBox<>();

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable3);

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable4);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Abas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AbasMouseClicked(evt);
            }
        });

        panel_equipamentos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panel_equipamentos.add(tf_nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 372, 137, -1));
        panel_equipamentos.add(tf_preco, new org.netbeans.lib.awtextra.AbsoluteConstraints(355, 372, 137, -1));
        panel_equipamentos.add(tf_nr_serie, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 413, 137, -1));
        panel_equipamentos.add(tf_fabricante, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 455, 137, -1));

        tf_data_fabr.setPreferredSize(new java.awt.Dimension(15, 24));
        panel_equipamentos.add(tf_data_fabr, new org.netbeans.lib.awtextra.AbsoluteConstraints(355, 455, 137, 20));

        bt_inserire.setText("Inserir");
        bt_inserire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_inserireActionPerformed(evt);
            }
        });
        panel_equipamentos.add(bt_inserire, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 520, 83, -1));

        bt_editare.setText("Editar");
        panel_equipamentos.add(bt_editare, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 520, 83, -1));

        bt_removere.setText("Remover");
        panel_equipamentos.add(bt_removere, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 520, 83, -1));

        jLabel1.setText("Nome:");
        panel_equipamentos.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 376, 35, -1));

        jLabel2.setText("Nro de Série: ");
        panel_equipamentos.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 417, -1, -1));

        jLabel3.setText("Fabricante:");
        panel_equipamentos.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 459, 59, -1));

        jLabel4.setText("Preço: ");
        panel_equipamentos.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(308, 376, 41, -1));

        jLabel5.setText("Data Fabricação:");
        panel_equipamentos.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(259, 457, -1, -1));

        table_chamados1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Número de Série", "Fabricante"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;}

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane6.setViewportView(table_chamados1);

        panel_equipamentos.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 502, 354));

        Abas.addTab("Equipamentos", panel_equipamentos);

        bt_removerc.setText("Remover");

        jLabel11.setText("Chamado: ");

        jLabel12.setText("Descrição");

        jLabel14.setText("Equipamento");

        jLabel15.setText("Data Abertura:");

        tf_data_ab.setPreferredSize(new java.awt.Dimension(15, 24));

        bt_inserirc.setText("Inserir");
        bt_inserirc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_inserircActionPerformed(evt);
            }
        });

        bt_editarc.setText("Editar");

        table_chamados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Título do Chamado", "Equipamento", "Data de Abertura", "Dias em aberto"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Integer.class
            };
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane5.setViewportView(table_chamados);

        javax.swing.GroupLayout panel_chamadosLayout = new javax.swing.GroupLayout(panel_chamados);
        panel_chamados.setLayout(panel_chamadosLayout);
        panel_chamadosLayout.setHorizontalGroup(
            panel_chamadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_chamadosLayout.createSequentialGroup()
                .addGroup(panel_chamadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_chamadosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane5))
                    .addGroup(panel_chamadosLayout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(bt_inserirc, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bt_editarc, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bt_removerc, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(panel_chamadosLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(panel_chamadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(panel_chamadosLayout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_chamado))
                    .addGroup(panel_chamadosLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_desc, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(panel_chamadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_chamadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(cb_equip, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tf_data_ab, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );
        panel_chamadosLayout.setVerticalGroup(
            panel_chamadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_chamadosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(panel_chamadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_chamadosLayout.createSequentialGroup()
                        .addGroup(panel_chamadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tf_chamado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addGap(29, 29, 29)
                        .addGroup(panel_chamadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tf_desc, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)))
                    .addGroup(panel_chamadosLayout.createSequentialGroup()
                        .addGroup(panel_chamadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cb_equip, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))
                        .addGap(26, 26, 26)
                        .addGroup(panel_chamadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(tf_data_ab, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(panel_chamadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_removerc)
                    .addComponent(bt_editarc)
                    .addComponent(bt_inserirc))
                .addContainerGap())
        );

        Abas.addTab("Chamados", panel_chamados);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Abas)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Abas)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void limpar() {
        tf_nome.setText("");
        tf_preco.setText("");;
        tf_nr_serie.setText("");
        tf_data_fabr.setText("");
        tf_fabricante.setText("");
        tf_chamado.setText("");
        tf_desc.setText("");
        tf_data_ab.setText("");
    }

    private void bt_inserireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_inserireActionPerformed
        double preco = 0;
        String nome = tf_nome.getText();
        int nro_serie = -1;
        String fabricante = tf_fabricante.getText();

        Date data_fabr = null;

        if (nome.length() < 6) {
            System.err.println("Insira um nome com mais de 6 caracteres");
        } else if (fabricante.equals("")) {
            System.err.println("Insira um Fabricante");
        } else {
            try {
                preco = Double.parseDouble(tf_preco.getText());
                try {
                    nro_serie = Integer.parseInt(tf_nr_serie.getText());
                    try {
                        SimpleDateFormat f = new SimpleDateFormat("dd/MM/yyyy");
                        data_fabr = f.parse(tf_data_fabr.getText());
                        Equipamentos equipa = new Equipamentos(nome, preco, nro_serie, data_fabr, fabricante);
                        equipamentos.add(equipa);
                    } catch (Exception e) {
                        System.err.println("Insira uma data válida");
                    }
                } catch (Exception e) {
                    System.err.println("Insira um numero de série válido!!!");
                }
            } catch (Exception e) {
                System.err.println("Insira um preço válido!!!");
            }
        }

    }//GEN-LAST:event_bt_inserireActionPerformed

    private void bt_inserircActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_inserircActionPerformed
        String chamado = tf_chamado.getText();
        String desc = tf_desc.getText();

        Date data_ab = null;

        int dias = 0;

        if (chamado != "") {
            System.err.println("Insira um título");
        } else if (desc == "") {
            System.err.println("Insira uma descrição");
        } else {
            try {
                SimpleDateFormat f = new SimpleDateFormat("dd/MM/yyyy");
                data_ab = f.parse(tf_data_ab.getText());
            } catch (Exception e) {
                System.err.println("Insira uma data válida");
            }
            try {
                Chamados c = new Chamados(chamado, desc, equipamentos.get(cb_equip.getSelectedIndex()), data_ab);
                chamados.add(c);
            } catch (Exception e) {
                System.err.println("Nenhum equipamento cadastrado");
            }
        }
    }//GEN-LAST:event_bt_inserircActionPerformed

    private void AbasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AbasMouseClicked
        cb_equip.removeAllItems();
        for (Equipamentos u : equipamentos) {
            cb_equip.addItem(u.getNome());
        }
    }//GEN-LAST:event_AbasMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Janela.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Janela.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Janela.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Janela.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Janela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane Abas;
    private javax.swing.JButton bt_editarc;
    private javax.swing.JButton bt_editare;
    private javax.swing.JButton bt_inserirc;
    private javax.swing.JButton bt_inserire;
    private javax.swing.JButton bt_removerc;
    private javax.swing.JButton bt_removere;
    private javax.swing.JComboBox<String> cb_equip;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JPanel panel_chamados;
    private javax.swing.JPanel panel_equipamentos;
    private javax.swing.JTable table_chamados;
    private javax.swing.JTable table_chamados1;
    private javax.swing.JTextField tf_chamado;
    private javax.swing.JFormattedTextField tf_data_ab;
    private javax.swing.JFormattedTextField tf_data_fabr;
    private javax.swing.JTextField tf_desc;
    private javax.swing.JTextField tf_fabricante;
    private javax.swing.JTextField tf_nome;
    private javax.swing.JTextField tf_nr_serie;
    private javax.swing.JTextField tf_preco;
    // End of variables declaration//GEN-END:variables
}
